Repository funidata/keijo, pull requests merged in 2024-05, with the labels that each got.

#71 Fix logic to show flex leave badge
  web/src/common/workdayUtils.ts
Labels: bug

#73 Icon button to jump to current week when browsing weeks
  web/src/components/workday-browser/WeekControl.tsx
  web/src/i18n/en.ts
  web/src/i18n/fi.ts
Labels: improvement

#72 Show alert and add button for missing zero hour entry when workday has flex leave entry
  web/src/common/workdayUtils.ts
  web/src/components/workday-accordion/WorkdayAccordion.tsx
  web/src/components/workday-accordion/workday-alert/AddZeroEntryAlert.tsx
  web/src/components/workday-accordion/workday-alert/AddZeroEntryButton.tsx
  web/src/i18n/en.ts
  web/src/i18n/fi.ts
Labels: improvement

#76 1.1.1
  package.json
  server/package-lock.json
  server/package.json
  web/package-lock.json
  web/package.json
Labels: exclude from release notes

#77 add tooltips for icon buttons
  web/src/components/entry-dialog/EntryDialog.tsx
  web/src/components/entry-dialog/EntryDialogButton.tsx
  web/src/components/language-select/LanguageSelect.tsx
  web/src/components/workday-accordion/entry-row/DeleteEntryButton.tsx
  web/src/components/workday-accordion/entry-row/EditEntryButton.tsx
  web/src/i18n/en.ts
  web/src/i18n/fi.ts
  web/src/theme/ColorModeToggle.tsx
Labels: improvement

#78 Fix error in navigating directly to '/create' urls
  web/src/components/entry-dialog/EntryDialog.tsx
  web/src/components/entry-dialog/EntryDialogButton.tsx
Labels: bug

#75 Add option to set workdays remaining hours automatically on entrydialog
  web/src/components/entry-dialog/EntryForm.tsx
  web/src/components/entry-dialog/useEntryForm.tsx
  web/src/components/entry-dialog/useFormSetRemainingHours.tsx
  web/src/components/user-preferences/usePreferSetRemainingHours.tsx
  web/src/i18n/en.ts
  web/src/i18n/fi.ts
Labels: new feature

#79 Hoist Prettier setup to project root
  .github/workflows/run_tests.yaml
  .gitignore
  .prettierignore
  .prettierrc.yaml
  package-lock.json
  package.json
  server/.eslintrc.yaml
  server/.prettierrc.yaml
  server/package-lock.json
  server/package.json
  server/src/netvisor/workday/entry.service.spec.ts
  server/test/app.e2e-spec.ts
  server/test/jest-e2e.json
  web/.prettierrc.yaml
  web/package-lock.json
  web/package.json
  web/public/favicon/site.webmanifest
  web/src/components/language-select/LanguageMenu.tsx
  web/src/components/workday-accordion/entry-row/EditEntryButton.tsx
  web/src/i18n/en.ts
  web/src/i18n/fi.ts
  web/vite.config.ts
Labels: exclude from release notes

#80 Setup Playwright to allow end-to-end testing
  .github/workflows/build_image.yaml
  .github/workflows/run_tests.yaml
  .gitignore
  .prettierignore
  README.md
  compose.yaml
  docs/development-handbook.md
  docs/tests.md
  e2e/.gitignore
  e2e/ci.env
  e2e/package-lock.json
  e2e/package.json
  e2e/playwright.config.ts
  e2e/tests-examples/demo-todo-app.spec.ts
  e2e/tests/example.spec.ts
  nv-mock/data/dimensionlist.nv.xml
  nv-mock/data/getrecordtypelist.nv.xml
  nv-mock/data/getworkdays.nv.xml
  nv-mock/nv-mock.json
  package.json
  scripts/version_sub_projects.sh
  server/Dockerfile
  server/package.json
  web/src/common/apolloClient.ts
  web/src/main.tsx
Labels: maintenance

#81 Add form for setting Entry form default values
  web/src/components/entry-dialog/DefaultsForm.tsx
  web/src/components/entry-dialog/DimensionComboBox.tsx
  web/src/components/entry-dialog/EntryDialog.tsx
  web/src/components/entry-dialog/EntryForm.tsx
  web/src/components/entry-dialog/useEntryForm.tsx
  web/src/components/layout/AppBar.tsx
  web/src/components/layout/AppMenu.tsx
  web/src/components/settings/SettingsMenu.tsx
  web/src/components/settings/SettingsSelect.tsx
  web/src/components/user-preferences/useDefaultEntryValues.tsx
  web/src/i18n/en.ts
  web/src/i18n/fi.ts
  web/src/router.tsx
Labels: new feature

#82 Refreshing with entry dialog open no longer crashes Keijo
  web/src/components/entry-dialog/EntryDialogButton.tsx
  web/src/components/entry-dialog/EntryForm.tsx
  web/src/components/entry-dialog/useEntryForm.tsx
  web/src/components/workday-accordion/entry-row/EditEntryButton.tsx
Labels: bug

#85 Bump version to 1.1.2
  e2e/package-lock.json
  e2e/package.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  web/package-lock.json
  web/package.json
Labels: exclude from release notes

#86 Fix edit dialog title
  web/src/components/BigDialog.tsx
  web/src/components/defaults-dialog/DefaultsDialog.tsx
  web/src/components/defaults-dialog/DefaultsForm.tsx
  web/src/components/entry-dialog/EntryDialog.tsx
  web/src/components/entry-dialog/EntryDialogButton.tsx
  web/src/components/layout/AppMenu.tsx
  web/src/components/settings/SettingsMenu.tsx
  web/src/i18n/en.ts
  web/src/i18n/fi.ts
  web/src/router.tsx
Labels: bug

#87 Mobile page delete entry button works again
  web/src/components/entry-dialog/EntryForm.tsx
Labels: bug

#89 Bump version 1.1.3
  e2e/package-lock.json
  e2e/package.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  web/package-lock.json
  web/package.json
Labels: exclude from release notes
