Repository funidata/keijo, pull requests merged in 2024-07, with the labels that each got.

#99 Add SSL mode to database connection configuration
  server/src/config/config.schema.ts
  server/src/config/config.ts
  server/src/database/migration-config.ts
  server/test/utils/mock-config.service.ts
Labels: bug

#101 Release v1.2.1
  e2e/package-lock.json
  e2e/package.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  web/package-lock.json
  web/package.json
Labels: exclude from release notes

#102 Update SSL configuration to use correct mode
  docs/configuration.md
  server/src/database/database-config.service.ts
  server/src/database/migration-config.ts
Labels: bug

#103 Release v1.2.2
  e2e/package-lock.json
  e2e/package.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  web/package-lock.json
  web/package.json
Labels: exclude from release notes

#105 Execute database migrations from Dockerfile for production-like environments
  .github/workflows/run_tests.yaml
  server/Dockerfile
Labels: maintenance

#106 Release v1.2.3
  e2e/package-lock.json
  e2e/package.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  web/package-lock.json
  web/package.json
Labels: exclude from release notes

#107 Fix set remaining hours option on current day
  web/src/components/entry-dialog/useEntryForm.tsx
Labels: bug

#109 Apply SSL configuration to express-session's database connection
  server/src/jira/session-setup.ts
  server/src/main.ts
  server/src/session/session.module.ts
Labels: bug, exclude from release notes

#110 Database migration to add session table
  server/src/database/migrations/1720525756096-create-session-table.ts
Labels: bug

#111 Update dependencies and eslint rules
  .github/workflows/release.yaml
  e2e/.eslintrc.yaml
  server/.eslintrc.yaml
  server/package-lock.json
  web/.eslintrc.yaml
  web/src/common/apolloClient.ts
  web/src/components/entry-dialog/useFormSetRemainingHours.tsx
Labels: maintenance

#112 Release v1.2.4
  e2e/package-lock.json
  e2e/package.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  web/package-lock.json
  web/package.json
Labels: exclude from release notes

#113 Add application version number to footer
  web/src/components/layout/ContentContainer.tsx
  web/src/components/layout/Footer.tsx
  web/src/vite-env.d.ts
  web/tsconfig.node.json
  web/vite.config.ts
Labels: maintenance

#116 Update deprecated docker/login-action
  .github/workflows/push_main.yaml
Labels: exclude from release notes

#117 Release v1.3.0
  e2e/package-lock.json
  e2e/package.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  web/package-lock.json
  web/package.json
Labels: exclude from release notes
